apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: to-monitor-deployment
  #namespace: to-monitor
  labels:
    app: to-monitor-app
spec:
  selector:
    matchLabels:
      app: to-monitor-app
  template:
    metadata:
      labels:
        app: to-monitor-app
    spec:
      containers:
        - name: to-monitor-app
          image: 956327719689.dkr.ecr.us-east-1.amazonaws.com/to-monitor:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 2000m
              memory: 4Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: TO_MOTHERSHIP_SERVICE_HOST
              value: "192.168.2.20"
            - name: TO_MOTHERSHIP_SERVICE_PORT
              value: "8080"

      terminationGracePeriodSeconds: 60
