---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: to-monitor-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: to-monitor-account
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: to-monitor-account
roleRef:
  kind: ClusterRole
  name: to-monitor-account
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: to-monitor-account
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: to-monitor
    app.kubernetes.io/component: to-monitor
    app.kubernetes.io/part-of: to-monitor
  name: to-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: to-monitor
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: to-monitor
      name: to-monitor
    spec:
      serviceAccount: to-monitor-account
      serviceAccountName: to-monitor-account
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: to-monitor
        image: 956327719689.dkr.ecr.us-east-1.amazonaws.com/to-monitor:1.0.3
        imagePullPolicy: Always
        env:
          - name: TO_CONFIG
            value: "eyJ0YXJnZXQiOiJ0by1wcm94eS1kZXYub3JjYXNlY3VyaXR5LmlvOjgwODAiLCJ0aWQiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAifQ=="
        securityContext:
          privileged: true
        volumeMounts:
          - name: hostroot
            mountPath: /node

      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      volumes:
      - hostPath:
          path: /
        name: hostroot
