apiVersion: v1
kind: PersistentVolume
metadata:
  name: to-redis-pv
  namespace: threatoptix
  labels:
    app: to-redis-app
    type: local
spec:
  storageClassName: ""
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/policystore"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: to-redis-pvc
  namespace: threatoptix
  labels:
    app: to-redis-app
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
