apiVersion: v1
kind: Service
metadata:
  name: to-mothership
  namespace: threatoptix
spec:
  selector:
    app: to-mothership-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
