apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    meta.helm.sh/release-name: conductor
    meta.helm.sh/release-namespace: threatoptix
  labels:
    app.kubernetes.io/instance: conductor
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: component
    helm.sh/chart: component-0.1.0
  name: conductor
  namespace: threatoptix
  resourceVersion: "2369633"
  uid: a103e6cf-0f29-4bfa-a000-0f8a4a8f10e2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: conductor
      app.kubernetes.io/name: component
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        releaseTime: 2023-04-24 09:40:44Z
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: conductor
        app.kubernetes.io/name: component
    spec:
      containers:
      - command:
        - ./start.sh
        envFrom:
        - configMapRef:
            name: conductor-config
        - secretRef:
            name: conductor-secret-store
        image: 956327719689.dkr.ecr.us-east-1.amazonaws.com/to-conductor:20230421112121
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        name: component
        ports:
        - containerPort: 8082
          name: conductor
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /v1/health
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 60
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1536Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: conductor
      serviceAccountName: conductor
      terminationGracePeriodSeconds: 20
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-19T10:02:27Z"
    lastUpdateTime: "2023-04-19T10:02:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-04-19T10:02:27Z"
    lastUpdateTime: "2023-04-24T09:41:17Z"
    message: ReplicaSet "conductor-5c646bcbf7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1