apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: mongodb
    meta.helm.sh/release-namespace: threatoptix
  creationTimestamp: "2023-04-19T06:57:34Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: mongodb-0.1.0
  name: mongodb
  namespace: threatoptix
  resourceVersion: "4373987"
  uid: e2a4cd86-c3b3-489d-884c-2c09c65c498a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: mongodb
      app.kubernetes.io/name: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: mongodb
        app.kubernetes.io/name: mongodb
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: mongodb-config
        - secretRef:
            name: mongodb-secrets
        image: mongo:6.0.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: mongodb
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: mongodb
        ports:
        - containerPort: 27017
          name: mongodb
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: mongodb
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mongodb
      serviceAccountName: mongodb
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: orcasecurity.io/services
        operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-04-19T06:57:34Z"
    lastUpdateTime: "2023-04-19T06:57:54Z"
    message: ReplicaSet "mongodb-7f6989ff6b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-04-29T00:10:24Z"
    lastUpdateTime: "2023-04-29T00:10:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1