apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-workers-deployment
  labels:
    app: kafka-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-worker
  template:
    metadata:
      labels:
        app: kafka-worker
    spec:
      containers:
        - name: kafka-worker-1
          image: 956327719689.dkr.ecr.us-east-1.amazonaws.com/to-pipeline:latest
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: SERVICE_NAME
              value: "events-processor"
            - name: PROCESS_NAME
              value: "ELFSCANNERPROCESS"
            - name: PROCESS_CONF_SUB_FOLDER
              value: "events-processor-raw-elfscanner"
            - name: GO_ENV
              value: "aws"
            - name: CONSUMER_BOOTSTRAP_SERVERS
              value: "b-1.test2.2wzuij.c8.kafka.us-east-1.amazonaws.com:9092"
            - name: PRODUCER_BOOTSTRAP_SERVERS
              value: "b-1.test2.2wzuij.c8.kafka.us-east-1.amazonaws.com:9092"
        - name: kafka-worker-2
          image: 956327719689.dkr.ecr.us-east-1.amazonaws.com/to-pipeline:latest
          env:
            - name: LOG_LEVEL
              value: "INFO"
            - name: SERVICE_NAME
              value: "events-processor"
            - name: PROCESS_NAME
              value: "WRITERPROCESS"
            - name: PROCESS_CONF_SUB_FOLDER
              value: "events-processor-writer"
            - name: GO_ENV
              value: "aws"
            - name: CONSUMER_BOOTSTRAP_SERVERS
              value: "b-1.test2.2wzuij.c8.kafka.us-east-1.amazonaws.com:9092"
            - name: PRODUCER_BOOTSTRAP_SERVERS
              value: "b-1.test2.2wzuij.c8.kafka.us-east-1.amazonaws.com:9092"